language: node_js
node_js:
- '6'
- node
sudo: false
deploy:
  provider: npm
  email: xo-npmjs.group@xogrp.com
  api_key:
    secure: TgEHAaLvnukuPmgKvF4WQdR/NU15hJGj3lrUgs5CvE2zQTWi6plPiWFR/QvFeJe0i2cExicFuEchO3msfKRCjh+2JKXHfkcI42a1do+49PtZQvGxdZPdIy50WMmJTh1s6uCiuvxHXpr9vB7phJp9VGRnArzblq2OAVOS2dQjehdqE0uLhQBP6ok633lZlslsVUr2BUyG+DEHKsX3V9BIw9a6imKzziSWIU9shOcfxWL7UpAZGBsx4rhy/0vlBfJMarUk1LLnvnXrSw+mfFokxYO1pYs/Gb1o5IhsKmEhJfTvALZweviuHZQBzjC5HGbd2j0o+Z8JqOGYTpvbDulWkm0A32nxQwhEYRcDmoNIPjlOR2CX2rTYJRsUvMmZablcb62VfOi9gSls97K6DSHk5yr1KpFmRt2AuGpJko9qKIkkff7P+tXf0/qwwd8hkJgHJz4tKRXK2vwNWH2GkXFGk7itL70cCWjMXSBMJDvHI32pW2bdgPizTIS1bXQPAWdLU+hPBEp4cdGMa5bS21fAX5+BW7aTAO7xrzizPq4whGSuzlbP045wvr3jJ+wSeXbdHcnpq33cr7TL89she7fLxMCcX4NIOiTqdRdEEYiYKNkdPRBjTYUT/A8HhGInZQKrHAst/46kAtI3PTEOhVwRp/LjyTMo6I5tpXBYeCCvXWI=
  on:
    tags: true
    repo: xogroup/toki
notifications:
  slack:
    secure: SDC8HqarnA8OmS7m7dK2PNxfP+mHI426udNc6vIF278cs6Wz++jDsYaQZ50ny0B/s1h4CXfzFa2UNDtPxPFwWj8FdiqGMMwi4DmGTsxEhTp7AM1HSqAlFMxijAjF5aySbBbM/uQG9SG0U3ECM+ftyXWRcXrOOPea+Lqyg7pqjiQu9sOfGid1SU+d9jZATJAiR8NW/fypQL3gA22t3Ndpq26hbWe/4xzYfclW7FrfEcCGj8WI4WhuhcIP9bMMbgG8TJrmLOyCIqSwMUZI9G7NlrAEpijwnKG/s7RR1SEWG1V6yNvIK4QBBuo9L77W6srMB1MfBJc0GH8tA27rSM7STgLMxP7zwZxihcF1bx51ZljzT26Ohk+4Rv84jmMxIbe14KE0C5OU6wbNiXAsvvgI9ehQa8cYBQxGsYbktk8EzxeUzCMP9TpENOXxrNf5vR8pzdEIR2UPGxGt9PE4VKAStIPhWqVnunp//igxnbsSQPAmPdePmWmMpH20Q7IbezS7zoAbEZxLn/k9I4tkkVPcTCUdnNVujUE+6+MntlUkE9YR5r0HiVLwsXzoSA8mR+FCPDMdmxeRtzYszJyvn84SsyWQlVPULTXgx6oFDc3LZfy7m8GJtvdFMCitR/xNdRBCLaycJRKRTQemNI/bG+SBTmMLXlbXAYTtcYUIpnERCX0=
