language: node_js
node_js:
- '6'
- node
sudo: false
deploy:
  provider: npm
  email: xo-npmjs.group@xogrp.com
  api_key:
    secure: fHwPOhfd+GrsWbtjPPkuaOdwYexZmrJOeG4QELHG8voV7HukRISi6o+R1FUdYRIM86ZkXGLzSXyQIej7ouSjlFhWaSwiAtjqxfsYuP05BYr/M1NrpNXkDmpwMbw3s22UGhuVXdW43/aIFFvHdg8tnLRjhLoLJmXCiuhtEsoqfa3XJSxCmASLkzcNUXh+89Eew/GeI/m6R0G0QaUfwR4KGmdmd10QC4N15m07oAqR0DchopXTiI2KkZpy0c0P5Yz3RKrtClUYWaWmFW/RMNNkWv8OLYfjK8hr03NRjClMv9cLlAiAdns7kSw1PAdwBLB+qcNTshCjgbsVP0IJLhwNVQ60KyjSBZV0LkgnXg7Mpy92ZRwnqTo6mUItTYAnC7OewWoBcZ6gDUVtCLZK2R78DtQAPNSnqyQ+z366jXYyfyT3A0e1ao9A9qWMjq/bEbOFc8Vp2oi0aHU0wjteCl6WyzTHa4wvPhKVc0pIhKOR366JurdaMA/cf7UXubflcip3KpzsW332sKs3Ib4ULPf4Xej+s5AHFgR4KgXjZJhS7B0Rk6ZEneygVpa9856VG7nwFJCgOsYwzx94V7MSFUOvCOK5Sc+7Dg6BmsTAy2Otxirdm3HWbVs0LliTcUmb42PmMsPghsLD+B1C1rAkviDlEo7uXgOpJvnkrE0oUAEfpu0=
  on:
    tags: true
    repo: xogroup/toki
notifications:
  slack:
    secure: SDC8HqarnA8OmS7m7dK2PNxfP+mHI426udNc6vIF278cs6Wz++jDsYaQZ50ny0B/s1h4CXfzFa2UNDtPxPFwWj8FdiqGMMwi4DmGTsxEhTp7AM1HSqAlFMxijAjF5aySbBbM/uQG9SG0U3ECM+ftyXWRcXrOOPea+Lqyg7pqjiQu9sOfGid1SU+d9jZATJAiR8NW/fypQL3gA22t3Ndpq26hbWe/4xzYfclW7FrfEcCGj8WI4WhuhcIP9bMMbgG8TJrmLOyCIqSwMUZI9G7NlrAEpijwnKG/s7RR1SEWG1V6yNvIK4QBBuo9L77W6srMB1MfBJc0GH8tA27rSM7STgLMxP7zwZxihcF1bx51ZljzT26Ohk+4Rv84jmMxIbe14KE0C5OU6wbNiXAsvvgI9ehQa8cYBQxGsYbktk8EzxeUzCMP9TpENOXxrNf5vR8pzdEIR2UPGxGt9PE4VKAStIPhWqVnunp//igxnbsSQPAmPdePmWmMpH20Q7IbezS7zoAbEZxLn/k9I4tkkVPcTCUdnNVujUE+6+MntlUkE9YR5r0HiVLwsXzoSA8mR+FCPDMdmxeRtzYszJyvn84SsyWQlVPULTXgx6oFDc3LZfy7m8GJtvdFMCitR/xNdRBCLaycJRKRTQemNI/bG+SBTmMLXlbXAYTtcYUIpnERCX0=
